#!/bin/bash

#
# Configuration file for default serial CPU tests
#

#-------------------------------------------------------------------------------
# Branches 
#
branch="master"
regtests_branch="master"

#-------------------------------------------------------------------------------
# Architecture
#
architecture="cpu-serial"

#-------------------------------------------------------------------------------
# CMake args
#
cmake_args+=("-DBUILD_TYPE=Debug")
cmake_args+=("-DPLATFORMS=SERIAL")

#-------------------------------------------------------------------------------
# OPALX args 
#
#opalx_args=()

#-------------------------------------------------------------------------------
# Unit tests args
#
#unittests_args=()

#-------------------------------------------------------------------------------
# Modules 
#
#module purge

module purge
module use unstable

module load gcc/15.2.0
module load openmpi/4.1.6_slurm
module load gnutls
module load Python
module load gnuplot
module load cmake/3.27.8
