#!/bin/bash

#
# Configuration file for default serial CPU tests
#

#-------------------------------------------------------------------------------
# Branches 
#
branch="master"
regtests_branch="master"

#-------------------------------------------------------------------------------
# Architecture
#
architecture="cpu-openmp"

#-------------------------------------------------------------------------------
# CMake args
#
cmake_args+=("-DBUILD_TYPE=Debug")
cmake_args+=("-DPLATFORMS=OPENMP")
cmake_args+=("-DOPALX_ENABLE_UNIT_TESTS=ON")

#-------------------------------------------------------------------------------
# OPALX args 
#
#opalx_args=()

#-------------------------------------------------------------------------------
# Unit tests: set to 'yes' to run ctest -L unit after build
#
do_unittests='yes'
#unittests_args=()

#-------------------------------------------------------------------------------
# Modules 
#
#module purge
